"use client";

/**
 * The feed.
 *
 * This replaced three things: a "Brief me on today" button, a scrolling strip
 * of statistics, and a standalone insights screen. All three asked the user
 * to go and get intelligence. This brings it to them, ranked, and gets out of
 * the way when there is nothing worth saying.
 *
 * Restraint is the feature:
 *
 *  - **At most three at once.** The fourth-most-important thing about your
 *    money on a given Tuesday is not important.
 *  - **No AI chrome.** No robot icon, no "generated by" label, no sparkles.
 *    The user wants to know they're short on the 14th; how we worked it out
 *    is what `evidence` is for.
 *  - **Nothing renders empty.** No skeletons, no "thinking…" — a signal
 *    appears when it exists and not a frame before.
 */

import { useState } from "react";
import Link from "next/link";
import { ChevronRight, X } from "lucide-react";
import { useAgentSignals } from "@/components/agent/agent-provider";
import type { Signal, SignalSeverity } from "@/lib/ai/agent/types";
import { cn } from "@/lib/utils";

const VISIBLE = 3;

const TONE: Record<SignalSeverity, string> = {
  critical: "border-destructive/40 bg-destructive/10",
  warn: "border-amber-400/30 bg-amber-400/10",
  info: "border-border bg-card shadow-soft",
};

const DOT: Record<SignalSeverity, string> = {
  critical: "bg-destructive",
  warn: "bg-amber-400",
  info: "bg-muted-foreground/40",
};

function SignalCard({ signal, onDismiss }: { signal: Signal; onDismiss: () => void }) {
  const [showEvidence, setShowEvidence] = useState(false);

  const body = (
    <div className="flex flex-1 flex-col gap-1">
      <div className="flex items-center gap-2">
        <span aria-hidden className={cn("size-1.5 shrink-0 rounded-full", DOT[signal.severity])} />
        <span className="text-[14px] font-medium">{signal.title}</span>
      </div>
      <p className="text-[13px] leading-relaxed text-muted-foreground">{signal.body}</p>
    </div>
  );

  return (
    <li
      className={cn(
        "flex flex-col gap-2 rounded-2xl border px-4 py-3.5 transition-[background-color,transform] duration-200 ease-spring",
        TONE[signal.severity],
      )}
    >
      <div className="flex items-start gap-3">
        {signal.href ? (
          <Link
            href={signal.href}
            className="flex flex-1 items-start gap-3 rounded-lg outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            {body}
            <ChevronRight aria-hidden className="mt-0.5 size-4 shrink-0 text-muted-foreground" />
          </Link>
        ) : (
          body
        )}
        {signal.dismissible && (
          <button
            type="button"
            aria-label={`Dismiss: ${signal.title}`}
            onClick={onDismiss}
            className="-mr-1 -mt-1 flex size-7 shrink-0 items-center justify-center rounded-full text-muted-foreground outline-none transition-colors hover:bg-accent hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring"
          >
            <X aria-hidden className="size-3.5" />
          </button>
        )}
      </div>

      {signal.evidence && signal.evidence !== signal.body && (
        <div>
          <button
            type="button"
            onClick={() => setShowEvidence((open) => !open)}
            aria-expanded={showEvidence}
            className="text-[12px] text-muted-foreground underline decoration-dotted underline-offset-2 outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            {showEvidence ? "Hide the numbers" : "Show the numbers"}
          </button>
          {showEvidence && (
            <p className="mt-1.5 text-[12px] leading-relaxed tabular-nums text-muted-foreground">
              {signal.evidence}
            </p>
          )}
        </div>
      )}
    </li>
  );
}

export function SignalFeed() {
  const { signals, dismiss } = useAgentSignals();
  const [expanded, setExpanded] = useState(false);

  if (signals.length === 0) return null;

  const shown = expanded ? signals : signals.slice(0, VISIBLE);
  const hidden = signals.length - shown.length;

  return (
    <section aria-label="What needs your attention" className="flex flex-col gap-2">
      <ul className="flex flex-col gap-2">
        {shown.map((signal) => (
          <SignalCard key={signal.id} signal={signal} onDismiss={() => dismiss(signal)} />
        ))}
      </ul>
      {hidden > 0 && (
        <button
          type="button"
          onClick={() => setExpanded(true)}
          className="self-start rounded-lg text-[13px] text-muted-foreground outline-none transition-colors hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring"
        >
          {hidden} more
        </button>
      )}
    </section>
  );
}
